input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} - %{LOGLEVEL:level} - %{GREEDYDATA:msg}" }
  }

  mutate {
    add_field => { "service" => "python-app" }
  }

# Add severity label based on log level
  if [level] == "INFO" {
    mutate { add_field => { "severity_label" => "LOW" } }
  } else if [level] == "WARNING" {
    mutate { add_field => { "severity_label" => "MEDIUM" } }
  } else if [level] == "ERROR" {
    mutate { add_field => { "severity_label" => "HIGH" } }
  }

  mutate {
    rename => { "level" => "severity" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}